# Generated by Django 2.0.7 on 2018-12-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0002_auto_20180409_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, null=True, unique=True)),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('expires_in', models.CharField(default=3600, max_length=512)),
                ('scope', models.CharField(max_length=512)),
                ('token_type', models.CharField(max_length=512)),
                ('last_updated', models.DateTimeField(default='2018-12-10 10:48:05+00:00')),
                ('last_submitted', models.DateTimeField(default='2018-12-10 10:48:05+00:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='googlefit_member', to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
