# Generated by Django 2.1.4 on 2018-12-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0002_auto_20180409_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('expiry_date', models.DateTimeField(default='2018-12-17 15:16:01+00:00', max_length=512)),
                ('scope', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='googlefit_member', to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
