# Generated by Django 2.0.4 on 2018-04-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0002_auto_20180409_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, null=True, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=500)),
                ('token_type', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
