# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 22:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_fitbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=2014)),
                ('response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('request_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FitbitMember',
            fields=[
                ('userid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=500)),
                ('token_type', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oh_fitbit.OpenHumansMember')),
            ],
        ),
    ]
