# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oh_fitbit', '0002_cacheitem_fitbitmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitmember',
            name='userid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='openhumansmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oh_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
