# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oh_fitbit', '0003_auto_20180331_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitbitmember',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitbitmember',
            name='userid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
